name: kitt-dev

services:
  postgres:
    image: postgres:17
    container_name: kitt_dev_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: commando
      POSTGRES_DB: kitt
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kitt_dev_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin


volumes:
  postgres_data_dev:
  pgadmin-data-dev: